name: CellCounter_venv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # Core scientific stack (conda-managed)
  - numpy=1.26.*
  - scikit-learn=1.7.*
  - pillow=10.*
  - matplotlib=3.*
  - ffmpeg
  - pyyaml
  - openssl
  - sqlite
  - tk
  - setuptools
  - wheel

  # PyTorch GPU via conda (robust across machines)
  - pytorch::pytorch=2.4.*
  - pytorch::torchvision=0.19.*
  - pytorch::torchaudio=2.4.*
  - pytorch-cuda=11.8  # requires NVIDIA driver >= 520

  # Everything else via pip.
  # IMPORTANT: we purposely REMOVE torch/torchvision/torchaudio/triton and ALL nvidia-cu12* packages here.
  - pip:
      - absl-py==2.3.1
      - affine==2.4.0
      - albucore==0.0.17
      - albumentations==1.4.18
      - alembic==1.14.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - asciitree==0.3.3
      - attrs==25.3.0
      - bioimageio-core==0.9.0
      - bioimageio-spec==0.5.4.3
      - bioio==3.0.0
      - bioio-base==3.0.0
      - bioio-ome-tiff==1.1.0
      - biopb==0.1.2
      - black==25.1.0
      - bokeh==3.7.3
      - cellpose==4.0.6
      - chex==0.1.90
      - choreographer==1.0.9
      - click==8.2.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - colorlog==6.9.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - dask==2025.7.0
      - dask-image==2024.5.3
      - dask-jobqueue==0.9.0
      - deprecated==1.2.18
      - detectron2==0.6
      - distributed==2025.7.0
      - distro==1.9.0
      - dnspython==2.7.0
      - efficientnet-pytorch==0.7.1
      - einops==0.8.1
      - elementpath==5.0.3
      - email-validator==2.2.0
      - etils==1.13.0
      - eval-type-backport==0.2.2
      - fasteners==0.19
      - fastremap==1.17.2
      - filelock==3.16.1
      - fill-voids==2.1.0
      - flax==0.10.4
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - fvcore==0.1.5.post20221221
      - genericache==0.4.1
      - geojson==3.2.0
      - gputil==1.4.0
      - greenlet==3.1.1
      - grpcio==1.74.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.7
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.3
      - humanize==4.12.3
      - hydra-core==1.3.2
      - imagecodecs==2023.9.18
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - instanseg-torch==0.0.9
      - iopath==0.1.9
      - jax==0.4.38
      - jaxlib==0.4.38           # CPU build (no jax-cuda* packages here)
      - jinja2==3.1.6
      - kaleido==1.0.0
      - kiwisolver==1.4.7
      - lacss==0.15.2
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - locket==1.0.0
      - logistro==1.1.0
      - loguru==0.7.3
      - lxml==6.0.0
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - msgpack==1.1.1
      - munch==4.0.0
      - mypy-extensions==1.1.0
      - narwhals==2.0.1
      - natsort==8.4.0
      - nd2==0.10.3
      - nest-asyncio==1.6.0
      - numcodecs==0.15.1
      - ome-types==0.6.1
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optax==0.2.5
      - optuna==4.4.0
      - orbax-checkpoint==0.11.5
      - orjson==3.11.1
      - packaging==25.0
      - palettable==3.3.3
      - pandas==2.3.1
      - partd==1.4.2
      - pathspec==0.12.1
      - pims==0.7
      - platformdirs==4.3.8
      - plotly==6.2.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - pretrainedmodels==0.7.4
      - protobuf==6.31.1
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pycocotools==2.0.7
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-extra-types==2.10.5
      - pydantic-settings==2.10.1
      - pygments==2.19.2
      - pynrrd==1.1.3
      - pyparsing==3.1.4
      - pyqt6==6.9.1
      - pyqt6-qt6==6.9.1
      - pyqt6-sip==13.10.2
      - pyqtgraph==0.13.7
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pywavelets==1.4.1
      - qtpy==2.4.3
      - rasterio==1.4.3
      - regex==2025.7.34
      - resource-backed-dask-array==0.1.0
      - rich==14.1.0
      - roifile==2025.5.10
      - ruyaml==0.91.0
      - safetensors==0.6.1
      - scikit-image==0.25.2
      - scipy==1.16.1
      - segment-anything==1.0
      - segmentation-models-pytorch==0.5.0
      - semver==3.0.4
      - shellingham==1.5.4
      - simplejson==3.20.1
      - six==1.17.0
      - slicerator==1.1.0
      - slideio==2.7.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.42
      - superqt==0.7.6
      - tabulate==0.9.0
      - tblib==3.1.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.76
      - termcolor==3.1.0
      - tifffile==2025.1.10
      - tiffslide==2.5.1
      - timm==1.0.19
      - tokenizers==0.21.4
      - toolz==1.0.0
      - tqdm==4.67.1
      - transformers==4.55.1
      - typer==0.12.5
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ultralytics==8.3.155
      - ultralytics-thop==2.0.14
      - vedo==2025.5.4
      - vtk==9.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xarray==2025.1.2
      - xmlschema==4.1.0
      - xsdata==24.3.1
      - xyzservices==2025.4.0
      - yacs==0.1.8
      - zarr==2.18.7
      - zict==3.0.0
      - zipp==3.20.2